spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb

server:
  port: 8080

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs