spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb

server:
  port: 8081

logging:
  level:
    root: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    resolve-schema-properties: true
    swagger-ui:
      path: /swagger-ui.html
  swagger-ui:
    url: /openapi/product-service-openapi.yaml

management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreakers

resilience4j:
  circuitbreaker:
    instances:
      myService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

  timelimiter:
    instances:
      myService:
        timeoutDuration: 2s